/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rTOUIaCuMSq
 */
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogHeader, DialogFooter, DialogContent, Dialog } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { PopoverTrigger, Popover } from "@/components/ui/popover"
import { clients } from "@/app/data"
import { Appointments, Clients } from "@/types/types"
import { useContext } from "react"
import { ClientContext } from "@/providers/ClientDataProvider"
import { redirect } from "next/navigation"
export function ClientForm() {
    return (
        <Dialog>
            <DialogTrigger asChild>
                <Button variant="outline">Schedule Appointment</Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <div className="flex justify-between items-center">
                        <DialogTitle>Schedule Appointment</DialogTitle>
                    </div>
                    <DialogDescription>Enter your details and pick a date and time for your appointment.</DialogDescription>
                </DialogHeader>
                <form className="grid gap-4 py-4" onSubmit={handleSubmit}>
                    <div className="grid grid-cols-2 items-center gap-4">
                        <div className="space-y-2">
                            <Label htmlFor="first-name">First name</Label>
                            <Input id="first-name" name="first-name" placeholder="Enter your first name" />
                        </div>
                        <div className="space-y-2">
                            <Label htmlFor="last-name">Last name</Label>
                            <Input id="last-name" name="last-name" placeholder="Enter your last name" />
                        </div>
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="location">Location</Label>
                        <Input id="location" name="location" placeholder="Enter your location" />
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="appointment-date">Appointment Date</Label>
                        <Popover>
                            <PopoverTrigger asChild>
                                <Input type="date" id="appointment-date" name="appointment-date" placeholder="Enter your appointment date" />
                            </PopoverTrigger>
                        </Popover>
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="appointment-date">Appointment Time</Label>
                        <Popover>
                            <PopoverTrigger asChild>
                                <Input type="time" id="appointment-time" name="appointment-time" placeholder="Enter your appointment date" />
                            </PopoverTrigger>
                        </Popover>
                    </div>
                    <DialogFooter>
                        <Button type="submit">Submit</Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    )
}
